pipeline {
    agent {
        kubernetes {
        label 'mypod'
        defaultContainer 'jnlp'
        yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: helm-deploy
spec:
  containers:
  - name: helm
    image: lachlanevenson/k8s-helm:v2.11.0
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /root/.kube
      name: kube-conf    
  - name: kubectl
    image: lachlanevenson/k8s-kubectl:v1.12.2
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /root/.kube
      name: kube-conf
  volumes:
  - name: kube-conf
    hostPath:
      path: /root/.kube/
      type: Directory
"""
        }
    }
    
    stages {
        
        stage('init helm && kubectl') {
            steps {
                container('kubectl') {
                    sh """
                    /usr/local/bin/kubectl get pod
                    """
                }
                container('helm') {
                    sh """
                    /usr/local/bin/helm init --upgrade --service-account tiller \
	                --skip-refresh -i kuops/tiller:v2.11.0 
	                /usr/local/bin/helm ls
                    """
                }
            }
        }

        stage('deploy dev') {
            
            steps {
                container('helm') {
                    sh """
                    pwd
                    helm  upgrade mysql-dev step2/mysql/ --install --namespace=dev --wait
                    helm  upgrade php-app step2/php/deploy/Charts --install --namespace=dev
                    """
                }
            }
        }

    }
}
