apiVersion: v1                                                                       
kind: PersistentVolumeClaim                                                          
metadata:                                                                            
  name: composer-home                                                                  
  namespace: default                                                                 
spec:                                                                                
  accessModes:                                                                       
  - ReadWriteMany                                                                    
  resources:                                                                         
    requests:                                                                        
      storage: 1Gi                                                                   
